import tkinter as TK
from tkinter import *
window = TK.Tk()
window.title("Calculator")
window.config(bg="Red")
window.geometry("640x430")
one = TK.Button(text = "    1   ")
two = TK.Button(text="  2   ")
three = TK.Button(text="    3   ")
four = TK.Button(text="   4   ")
five = TK.Button(text="   5    ")
six = TK.Button(text="  6   ")
seven = TK.Button(text="    7   ")
eight = TK.Button(text="    8   ")
nine = TK.Button(text="    9    ")
zero = TK.Button(text="    0    ")

one.grid(row = 0, column = 0, sticky = W, pady = 2)
two.grid(row = 0, column = 1, sticky = W, pady = 2)
three.grid(row = 0, column = 2, sticky = W, pady = 2)
four.grid(row = 1, column = 0, sticky = W, pady = 2)
five.grid(row = 1, column = 1, sticky = W, pady = 2)
six.grid(row = 1, column = 2, sticky = W, pady = 2)
seven.grid(row = 2, column = 0, sticky = W, pady = 2)
eight.grid(row = 2, column = 1, sticky = W, pady = 2)
nine.grid(row = 2, column = 2, sticky = W, pady = 2)
zero.grid(row = 3, column = 1, sticky = W, pady = 2)
window.mainloop()