import tkinter as TK
window = TK.Tk()
window.geometry("640x430")
window.config(bg="teal")
window.title("Advertising Form")
def display_form():
    print(company_entry.get())
    print(name_entry.get())
    print(email_entry.get())
    print(phone_entry.get())
name_label=TK.Label(text="Please enter your name")
name_label.pack(pady=5)
name_entry=TK.Entry()
name_entry.pack(pady=10)
company_label = TK.Label(text="please enter your company")
company_label.pack(pady=15)
company_entry = TK.Entry()
company_entry.pack(pady=20)
email_label = TK.Label(text="Please enter your email")
email_label.pack(pady=25)
email_entry = TK.Entry()
email_entry.pack(pady=30)
phone_label =TK.Label(text="Please enter your phone number")
phone_label.pack(pady=35)
phone_entry = TK.Entry()
phone_entry.pack(pady=40)
submit=TK.Button(text="submit",command=display_form)
submit.pack()

window.mainloop()